/*
 * src/gui/browser_widget.cpp - Implementation of the browser widget
 * Copyright (c) 2026 Kirn Gill II
 * SPDX-License-Identifier: MIT
 * See LICENSE file for full license text.
 */

#include "browser_widget.h"
#include <QRegularExpression>

namespace efgrabber {

BrowserWidget::BrowserWidget(QWidget* parent)
    : QWidget(parent)
{
    setupUi();
}

void BrowserWidget::setupUi() {
    mainLayout_ = new QVBoxLayout(this);
    mainLayout_->setContentsMargins(0, 0, 0, 0);

    // Navigation bar
    navLayout_ = new QHBoxLayout();

    backButton_ = new QPushButton("<");
    backButton_->setMaximumWidth(30);
    navLayout_->addWidget(backButton_);

    forwardButton_ = new QPushButton(">");
    forwardButton_->setMaximumWidth(30);
    navLayout_->addWidget(forwardButton_);

    urlEdit_ = new QLineEdit();
    urlEdit_->setPlaceholderText("Enter URL...");
    urlEdit_->setText("https://www.justice.gov/epstein/doj-disclosures");
    navLayout_->addWidget(urlEdit_);

    goButton_ = new QPushButton("Go");
    connect(goButton_, &QPushButton::clicked, this, &BrowserWidget::onGoClicked);
    navLayout_->addWidget(goButton_);

    mainLayout_->addLayout(navLayout_);

#ifdef HAVE_WEBENGINE
    webView_ = new QWebEngineView(this);
    mainLayout_->addWidget(webView_);

    connect(urlEdit_, &QLineEdit::returnPressed, this, &BrowserWidget::onGoClicked);
    connect(backButton_, &QPushButton::clicked, webView_, &QWebEngineView::back);
    connect(forwardButton_, &QPushButton::clicked, webView_, &QWebEngineView::forward);
    connect(webView_, &QWebEngineView::urlChanged, this, &BrowserWidget::onUrlChanged);
    connect(webView_, &QWebEngineView::loadFinished, this, &BrowserWidget::onLoadFinished);

    // Listen for cookie changes
    QWebEngineCookieStore* cookieStore = webView_->page()->profile()->cookieStore();
    connect(cookieStore, &QWebEngineCookieStore::cookieAdded,
            this, &BrowserWidget::onCookieAdded);
    connect(cookieStore, &QWebEngineCookieStore::cookieRemoved,
            this, &BrowserWidget::onCookieRemoved);

    // Initial navigation
    webView_->setUrl(QUrl("https://www.justice.gov/epstein/doj-disclosures"));
#else
    placeholderLabel_ = new QLabel("WebEngine not available.\n\n"
                                   "To use the browser, rebuild with Qt5 WebEngine:\n"
                                   "sudo apt install qtwebengine5-dev\n\n"
                                   "Alternatively, export cookies from your browser\n"
                                   "and use the Cookie File option.");
    placeholderLabel_->setAlignment(Qt::AlignCenter);
    placeholderLabel_->setStyleSheet("background-color: #f0f0f0; padding: 20px;");
    mainLayout_->addWidget(placeholderLabel_);

    backButton_->setEnabled(false);
    forwardButton_->setEnabled(false);
    goButton_->setEnabled(false);
#endif

    statusLabel_ = new QLabel("Browse to justice.gov - cookies will transfer automatically");
    mainLayout_->addWidget(statusLabel_);
}

void BrowserWidget::navigateTo(const QString& url) {
#ifdef HAVE_WEBENGINE
    webView_->setUrl(QUrl(url));
#endif
    urlEdit_->setText(url);
}

QString BrowserWidget::currentUrl() const {
#ifdef HAVE_WEBENGINE
    return webView_->url().toString();
#else
    return urlEdit_->text();
#endif
}

QString BrowserWidget::getCookieString(const QString& domain) const {
#ifdef HAVE_WEBENGINE
    QStringList cookieParts;
    for (const auto& cookie : cookies_) {
        QString cookieDomain = cookie.domain();
        // Match if cookie domain matches or is a parent of the requested domain
        if (domain.endsWith(cookieDomain) || cookieDomain.endsWith(domain) ||
            cookieDomain == "." + domain || domain == cookieDomain.mid(1)) {
            cookieParts.append(QString::fromUtf8(cookie.name()) + "=" +
                             QString::fromUtf8(cookie.value()));
        }
    }
    return cookieParts.join("; ");
#else
    Q_UNUSED(domain);
    return QString();
#endif
}

QString BrowserWidget::getCookiesNetscapeFormat() const {
#ifdef HAVE_WEBENGINE
    QStringList lines;
    lines.append("# Netscape HTTP Cookie File");
    lines.append("# Generated by efgrabber browser");
    lines.append("");

    for (const auto& cookie : cookies_) {
        QString domain = cookie.domain();
        if (!domain.startsWith(".")) {
            domain = "." + domain;
        }
        bool hostOnly = !cookie.domain().startsWith(".");
        QString secure = cookie.isSecure() ? "TRUE" : "FALSE";
        qint64 expiry = cookie.expirationDate().isValid()
                      ? cookie.expirationDate().toSecsSinceEpoch()
                      : 0;

        lines.append(QString("%1\t%2\t%3\t%4\t%5\t%6\t%7")
            .arg(domain)
            .arg(hostOnly ? "FALSE" : "TRUE")
            .arg(cookie.path())
            .arg(secure)
            .arg(expiry)
            .arg(QString::fromUtf8(cookie.name()))
            .arg(QString::fromUtf8(cookie.value())));
    }
    return lines.join("\n");
#else
    return QString();
#endif
}

bool BrowserWidget::hasCookiesFor(const QString& domain) const {
#ifdef HAVE_WEBENGINE
    for (const auto& cookie : cookies_) {
        QString cookieDomain = cookie.domain();
        if (domain.endsWith(cookieDomain) || cookieDomain.endsWith(domain) ||
            cookieDomain == "." + domain || domain == cookieDomain.mid(1)) {
            return true;
        }
    }
    return false;
#else
    Q_UNUSED(domain);
    return false;
#endif
}

#ifdef HAVE_WEBENGINE
QWebEngineProfile* BrowserWidget::profile() const {
    return webView_->page()->profile();
}
#endif

void BrowserWidget::goToDataSet(int dataSet) {
    QString url = QString("https://www.justice.gov/epstein/doj-disclosures/data-set-%1-files").arg(dataSet);
    navigateTo(url);
}

void BrowserWidget::fetchPageForScraping(const QString& url) {
#ifdef HAVE_WEBENGINE
    // Load the URL and when done, emit the HTML
    webView_->setUrl(QUrl(url));
    // The HTML will be emitted in onLoadFinished via pageHtmlReady signal
#else
    Q_UNUSED(url);
#endif
}

void BrowserWidget::onGoClicked() {
    QString url = urlEdit_->text();
    if (!url.startsWith("http://") && !url.startsWith("https://")) {
        url = "https://" + url;
    }
    navigateTo(url);
}

void BrowserWidget::onUrlChanged(const QUrl& url) {
    urlEdit_->setText(url.toString());
    emit urlChanged(url.toString());
}

void BrowserWidget::onLoadFinished(bool ok) {
    if (ok) {
#ifdef HAVE_WEBENGINE
        int cookieCount = cookies_.size();
        int justiceCookies = 0;
        for (const auto& cookie : cookies_) {
            if (cookie.domain().contains("justice.gov")) {
                justiceCookies++;
            }
        }
        statusLabel_->setText(QString("Page loaded - %1 cookies (%2 for justice.gov)")
            .arg(cookieCount).arg(justiceCookies));

        // Get page HTML and emit for scraping + scan for PDF links
        webView_->page()->toHtml([this](const QString& html) {
            // Emit HTML for scraper to use
            emit pageHtmlReady(webView_->url().toString(), html);
            scanForPdfLinks(html);
        });
#else
        statusLabel_->setText("Page loaded");
#endif
    } else {
        statusLabel_->setText("Page load failed");
    }
}

#ifdef HAVE_WEBENGINE
void BrowserWidget::onCookieAdded(const QNetworkCookie& cookie) {
    QString key = cookie.domain() + ":" + QString::fromUtf8(cookie.name());
    cookies_[key] = cookie;
    emit cookiesChanged();
}

void BrowserWidget::onCookieRemoved(const QNetworkCookie& cookie) {
    QString key = cookie.domain() + ":" + QString::fromUtf8(cookie.name());
    cookies_.remove(key);
    emit cookiesChanged();
}
#endif

void BrowserWidget::scanForPdfLinks(const QString& html) {
    // Look for EFTA PDF links
    QRegularExpression re(R"(EFTA(\d{8})\.pdf)", QRegularExpression::CaseInsensitiveOption);
    QRegularExpressionMatchIterator it = re.globalMatch(html);

    int count = 0;
    while (it.hasNext()) {
        QRegularExpressionMatch match = it.next();
        QString fileId = "EFTA" + match.captured(1);
        count++;
        emit pdfLinkFound(fileId, "");
    }

    if (count > 0) {
        statusLabel_->setText(statusLabel_->text() + QString(" - Found %1 PDF links").arg(count));
    }
}

} // namespace efgrabber
